### ISSUE TITLE
Prefix handling?

### ISSUE THREAD

**Issue by oliverjanik** [twitchax/AspNetCore.Proxy#1]
Do you support prefix handling? 

Say everything that hits /subpath  goes to http://example.com

E.g. /subpath/script.js  would go to http://example.com/script.js

**Comment by twitchax** [comment]
@oliverjanik, actually, you can already do this, but I did not know it was a thing.  I am using the builtin ASP.NET Core template router, which has a `*` semantic for this.  I added a test for this scenario, and it is shown off [here](https://github.com/twitchax/AspNetCore.Proxy/blob/master/src/Test/UnitTests.cs#L187).
