### ISSUE TITLE
Is there exmaple using your proxy with JWT? I want to check the auth in the proxy like api gateway

### ISSUE THREAD

**Issue by shalomda** [twitchax/AspNetCore.Proxy#107]

**Comment by twitchax** [comment]
Currently, no, but you could suggest an example.

You likely want to use this example.

```csharp
.WithBeforeSend((c, hrm) =>
        {
            // Set something that is needed for the downstream endpoint.
            hrm.Headers.Authorization = new AuthenticationHeaderValue("Basic");

            return Task.CompletedTask;
        })
```

**Comment by VishCapG** [comment]
@twitchax  How can we implement this token auth with 

app.RunProxy(proxy => proxy.UseHttp("https://reqres.in/"));

basically i want to pass it with all the request to for eg. https://reqres.in/

**Comment by vishalv26** [comment]
@twitchax  how can we implement the above example?

basically i want to pass token with all the request
 something to compliment 
 app.RunProxy(proxy => proxy.UseHttp("http://google.com"));
In essence, I aim to forward all requests as they are, but with the addition of an authentication token. Could you please provide some suggestions or guidance on how to achieve this? Thank you

**Comment by twitchax** [comment]
Yep, basically, you use the example from the README.  The way ASP.NET works is that you can do pretty much whatever you want with the `context` in here.

```csharp
app.RunProxy(proxy => proxy
    .UseHttp((context, args) =>
    {
        // Check the auth token here by inspecting `context.Request.Headers` (or something like that).

        return "http://myhttpserver.com";
    })
    .UseWs((context, args) => "ws://mywsserver.com"));
```

**Comment by vishalv26** [comment]
Thank you so much @twitchax 👯‍♂️
