### ISSUE TITLE
Loading proxy endpoints in swagger

### ISSUE THREAD

**Issue by Matthew-Oduamafu** [twitchax/AspNetCore.Proxy#111]
Hello @twitchax kindly provide example code how to get the proxy endpoints in swagger

**Comment by twitchax** [comment]
If you're using the registered routes (i.e., `[Route("api/posts/{postId}")]`), then this should "just work" with your usual method of generating swagger definitions.

**Comment by Matthew-Oduamafu** [comment]
Thanks @twitchax
