### ISSUE TITLE
Authentication Token

### ISSUE THREAD

**Issue by baoduy** [twitchax/AspNetCore.Proxy#12]
It really nice library for B2B communication. I just have a small question regarding to authentication when calling the second API.

Thanks 
Duy

**Comment by twitchax** [comment]
@baoduy, cool, what's your question?

**Comment by baoduy** [comment]
@twitchax As you know each API has it own authentication and authorization, How could I apply the authentication context when using this library?

**Comment by twitchax** [comment]
If you use a [built-in controller](https://github.com/twitchax/AspNetCore.Proxy#existing-controller), you can use your existing Web API authentication without and issues.
