### ISSUE TITLE
POST Handling? 

### ISSUE THREAD

**Issue by TonyAdamo** [twitchax/AspNetCore.Proxy#13]
Is AspNetCore.Proxy able to handle POST requests? If so, is there documentation that can be provided for it?

**Comment by twitchax** [comment]
@TonyAdamo, yes, good idea on adding docs.

Also, yes.  The HTTP METHOD and headers are forwarded as best as possible, so all you have to do is compute the proxied address.  All HTTP METHODs will just be sent over the wire to the proxied address as they were received.

Take a look at the tests for a POST example or two.

**Comment by twitchax** [comment]
Closing since question answered.
