### ISSUE TITLE
Custom process response for one of ther proxy url

### ISSUE THREAD

**Issue by urffin** [twitchax/AspNetCore.Proxy#15]
Is it possibly add custom process response for specifix proxy url?

For example:

proxy url

    app.UseProxy("api/{*proxy}", (context, routeData) => $"https://custom.domain/{routeData["proxy"]}{context.Request.QueryString}");

for url "https://custom.domain/jsonresult" returned json string like

    "{\"param1\":  \"param1_value\"}"

Can i somehow modify it just for this url before returning?

**Comment by twitchax** [comment]
@urffin, I'm not sure I understand.

You want to proxy a request; then, modify the proxied response before passing it back to the client?

If yes, then that is currently _not_ possible, but likely an easy addition.

**Comment by urffin** [comment]
@twitchax, Yes, indeed _modify the proxied response before passing it back to the client_!

Easy addition in lib or where?

**Comment by urffin** [comment]
@twitchax, as i understand changes should be in [this](https://github.com/twitchax/AspNetCore.Proxy/blob/master/src/Core/Helpers.cs#L112) place?

    using (var responseStream = await responseMessage.Content.ReadAsStreamAsync().ConfigureAwait(false))
    {
        await responseStream.CopyToAsync(response.Body, 81920, context.RequestAborted).ConfigureAwait(false);
    }

before writing to `reponse.Body`

**Comment by twitchax** [comment]
@urffin, correct.  I can do this sometime soon™, or I would be happy to take a PR.  Basically, a callback that allows modification should be plumbed through all of the ways you can define a proxy, with a default `null` value.

**Comment by urffin** [comment]
@twitchax :) i need look it deeper :) not clear what should return this callback: stream as parameter and stream as return value?

**Comment by twitchax** [comment]
Addressing with #23.
