### ISSUE TITLE
WebSocket support?

### ISSUE THREAD

**Issue by Rohansi** [twitchax/AspNetCore.Proxy#16]
Is it possible to proxy WebSocket connections? Would there be any issues with timeouts?

**Comment by twitchax** [comment]
Hi @Rohansi, the current implementation does not, but it is likely possible.  I have not done any research in this area yet.

**Comment by twitchax** [comment]
Hi @Rohansi, I finally got off my ass and did this.  Coming soon!

**Comment by twitchax** [comment]
Addressing in #26.
