### ISSUE TITLE
Any way to add headers or cookies to the request?

### ISSUE THREAD

**Issue by digitalpowers** [twitchax/AspNetCore.Proxy#22]
Since we can only provide the uri you are getting I dont see any way to add an authorization header or a cookie for example?

I didnt see a way but I figured I should ask before i just wondered off.

**Comment by twitchax** [comment]
Hi @digitalpowers, I am working on this right now.  Want me to add you to PR?

**Comment by digitalpowers** [comment]
sure, i think it is the only feature this is missing for my use :)

**Comment by twitchax** [comment]
Addressing with #23.
