### ISSUE TITLE
HTTPS support.

### ISSUE THREAD

**Issue by RyanDrx** [twitchax/AspNetCore.Proxy#24]
If we want to use https for the call to the proxy server. Then we have to add an unnamed httpClient
` services.AddHttpClient("", c => ` and configure the certificate handler there.

Can we pass the name of the HttpClient name as proxy option?

**Comment by twitchax** [comment]
Hi @RyanDrx, this is a good idea.  However, do you mean for the call to the proxy server, or the call to the proxied endpoint?

**Comment by RyanDrx** [comment]
Hi, thanks for the quick response. 
I mean the call to the proxied endpoint.

**Comment by twitchax** [comment]
Something like this?

https://github.com/twitchax/AspNetCore.Proxy/pull/25

**Comment by RyanDrx** [comment]
Exactly! Thanks

**Comment by twitchax** [comment]
Great!
