### ISSUE TITLE
WebSocket interception support

### ISSUE THREAD

**Issue by JakeSmokie** [twitchax/AspNetCore.Proxy#27]
Is there any possible way to intercept websocket requests?

Mostly probable that ProxyOptions.WithIntercept is not supposed to handle this case

**Comment by twitchax** [comment]
@JakeSmokie, I plan on implementing this.  I am in the middle of doing a big redesign, and this feature is on my list of TODOs.  At the moment, based on the current design, WebSocket support is kind of a second-class citizen, so I want to address that.

**Comment by ferenc-a** [comment]
Was this feature actually completed? The function I pass to `WsProxyOptionsBuilder.Instance.WithIntercept(` only gets called once, on the HTTP connection that upgrades to a WebSocket. I can't actually intercept the traffic on WebSocket after this, and it looks like I can't access the WS connection after calling `WsProxyAsync`, so I can't even handle it with other tools.

**Comment by ferenc-a** [comment]
It was not clear for me before, there was no reference to the upgrade here. I made a new issue for it then: https://github.com/twitchax/AspNetCore.Proxy/issues/121.
Btw, your link is to some YouTube video, not a code todo.

**Comment by twitchax** [comment]
Ha, sorry.  Fixed.
