### ISSUE TITLE
Problems with POST proxy from Controller to another Controller with [FromBody]

### ISSUE THREAD

**Issue by davesofthunder** [twitchax/AspNetCore.Proxy#30]
I have a .NET Core Web App that has Controller endpoints that I want to forward to another .NET Core Web App with identically named controller methods.  This library works great for the GET requests (thank you!) but I am having problems with the proxy when attempting a POST with the model binding and the [FromBody] attribute.

For example, using a simple POCO model such as this:

```
     public class SimpleModel
     {
        public string MyProperty { get; set; }
        public string AnotherProperty {get; set}
     }

```
In the source Web app controller - I have a POST method such as this.  When I post application/json from PostMan, using JSON body of the request, I can hit this controller endpoint and the model binding correctly populates the model.

```

    [Route("api/[controller]")]
public class MySourceController : Controller
{
    [HttpPost]
    public Task Post([FromBody] SimpleModel model)
   {
         var options = ProxyOptions.Instance;
         return this.ProxyAsync($"http://localhost:60909/api/mydest", options);
    }
}
```

In my second running web app controller, I have another controller that takes the same model parameter as a POST request.

```

    [Route("api/[controller]")]
    public class MyDestController : Controller
   {
         [HttpPost]
         public IActionResult Post([FromBody] SimpleModel model)
        {
            // do something here with the request
           return Ok();
    }
 }
```
The Destination controller never gets hit.  If I remove the [FromBody] attribute from the destination controller signature, the endpoint will get hit, but the model parameter is null.

I am wondering if there is some other type of config I need to do to get this to work.  Is it possible to show an example of proxying via POST to an endpoint that uses the [FromBody] tag?

Thanks!

**Comment by twitchax** [comment]
@davesofthunder, this is a shot in the dark, but I have a guess.

Remove the `[FromBody]` and parameter from the proxy controller.  `ProxyAsync` handles the body, so I suspect that using the parameter may read the body from the stream, thereby removing it before the proxy method can pass it along.

**Comment by davesofthunder** [comment]
> @davesofthunder, this is a shot in the dark, but I have a guess.
> 
> Remove the `[FromBody]` and parameter from the proxy controller. `ProxyAsync` handles the body, so I suspect that using the parameter may read the body from the stream, thereby removing it before the proxy method can pass it along.

That did the trick! It works - thanks so much.

**Comment by twitchax** [comment]
Cool!  I will update the docs to point out that the helper method has to be called from a parameterless controller.

**Comment by twitchax** [comment]
Updated docs.
