### ISSUE TITLE
Edit reponse

### ISSUE THREAD

**Issue by ElAmen** [twitchax/AspNetCore.Proxy#31]
Is it possible to intercept and edit the proxy's response before returning it to the user?

**Comment by twitchax** [comment]
Yes!

Check out `AfterReceive` on the options.

**Comment by szalapski** [comment]
But I gather there's no good way to add a JSON property or two without deserializing, right?

**Comment by twitchax** [comment]
Correct, that is unavoidable in any proxy case.
