### ISSUE TITLE
Library depends on Microsoft.Extensions.Http version 3.0

### ISSUE THREAD

**Issue by ahumeniy** [twitchax/AspNetCore.Proxy#32]
I can't upgrade this library to the 3.1.0 version because my project uses ASPNET Core 2.1. I tried to upgrade to Core 2.2, but I get several errors because I'm asked to add several Core 3 libraries and some of those conflicts with my existing project. 

I tried to compile the project myself changing the dependency to Microsoft.Extensions.Http version 2.2 as it was on the previous release and I don't see any problems so far. Is there a reason for this requirement?

Greetings,

**Comment by twitchax** [comment]
I just pushed a new package which drops this version. :)

**Comment by ahumeniy** [comment]
Thanks!
