### ISSUE TITLE
Custom response without using HttpProxyOptions

### ISSUE THREAD

**Issue by psneo** [twitchax/AspNetCore.Proxy#41]
Would like to check if it is possible to return a task with my custom response instead of modifying the response after proxy using HttpProxyOption. This is to save overhead so that i can handle responses that does not need to be proxied.

For example:

```
public class MyController : Controller
{
    [Route("api/posts/{postId}")]
    public Task GetPosts(int postId)
    {
       string country = HttpContext.Request.Query["Country"].ToString();
       if(country != "Usa")
       {
          return Task.FromResult("Not a vaild country")
       }
       else
       {
            return this.HttpProxyAsync($"https://jsonplaceholder.typicode.com/posts/{postId}");
        }
    }
}
```

I tested the above scenario and it doesnt return any value from Task.FromResult("Not a vaild country"). It does work if the return type is changed to **Task\<string\>**. However, the code will not compile since  **this.HttpProxyAsync($"https://jsonplaceholder.typicode.com/posts/{postId}")** is returning a different type.
Is there any solution to this?

Thank you very much for this project and for the help.

**Comment by twitchax** [comment]
Hi @psneo,

The problem is that ASP.NET will act differently if you use a different return type.  When you return a `Task<String>, it expects all code paths to returns a `string` that can be written to the response.  In the proxying case, we do not want ASP.NET to write to the response, since we have already written to it.

However, you can use the `WithIntercept` option.

``csharp
public class MyController : Controller
{
    private HttpProxyOptions _options = HttpProxyOptionsBuilder.Instance
        WithIntercept(async context =>
        {
            if(country != "Usa")
            {
                c.Response.StatusCode = 300;
                await c.Response.WriteAsync("I don't like this port, so I am not proxying this request!");
                return true;
             }

            return false;
        });

    [Route("api/posts/{postId}")]
    public Task GetPosts(int postId)
    {
        return this.HttpProxyAsync($"https://jsonplaceholder.typicode.com/posts/{postId}", _options);
    }
}
```

**Comment by psneo** [comment]
Thanks for the explanation. You made it clearer. Thanks!
