### ISSUE TITLE
What would be the websocket url when use [Route("ws")]

### ISSUE THREAD

**Issue by shasanji** [twitchax/AspNetCore.Proxy#45]
Hi 
I wanted to implement controller with ws, as a example i have implemented as bellow. But not sure how to call url from websocket client. Other proxy examples worked for me. Thank you very much.

 `
    public class TestController : Controller
    {
        [Route("ws")]
        public Task OpenWs()
        {
            Console.WriteLine("Request came through");
            return this.WsProxyAsync($"ws://mywsendpoint.com/ws");
        }
    }
`

**Comment by twitchax** [comment]
@shasanji, you need to have a websocket client connect to `ws://yourserveraddress/ws`, in this case.

However, I am not sure I completely understand the question.

**Comment by shasanji** [comment]
Hi Aaron
Thank you very much getting back to me. I have tested the AspNetCore.Proxy and work fine with me when i call http proxy(this.HttpProxyAsync). But when i call ws(web socket) didn't work for me. Local url i used http://localhost:5000. I wasn't sure what port and url should use(meaning not get call 'OpenWs method when my url is ws://localhost:5000/ws'). I am using chorm extension as my ws client.

**Comment by twitchax** [comment]
There is a test for web sockets that might help you get it working as an example.  Check out `src/Test/Ws`.

**Comment by shasanji** [comment]
Hi Aaron
Thank you very much that help me lot.
regards
Shashi

**Comment by twitchax** [comment]
Sons good!
