### ISSUE TITLE
Using configured HttpClient as the base address

### ISSUE THREAD

**Issue by Nysosis** [twitchax/AspNetCore.Proxy#47]
(First, thanks for the really useful library!)

I think it'd be helpful if you could configure the proxy with the base URI specified, so all proxied requests from controllers can just be relative URLs, but right now this doesn't work because `HttpProxyAsync` validates the URL string starts with http/https, and doesn't resolve it with relation to the HttpClient it's going to use.

Additionally, it'd be nice if `app.RunProxy((proxy) => proxy.UseHttp("https://youraccountuat.southernwater.co.uk"))` and it's ilk took this into consideration also, so we don't need to specify the root URL multiple times.

When configuring with:
```
services.AddProxies((client) => client.BaseAddress = new Uri("https://myproxiedurl", UriKind.Absolute));
```

or alternatively configured HttpClients

```
services.AddHttpClient("MyProxyClient", (c) => c.BaseAddress = new Uri("https://myproxiedurl", UriKind.Absolute));
```
and then passed through with
```
return this.HttpProxyAsync("/my-proxy-path", HttpProxyOptionsBuilder.Instance.WithHttpClientName("MyProxyClient").Build());
```
 where applicable

**Comment by twitchax** [comment]
Cool idea.  I should be able to do that.  I will probably add a helper method to the builders.

**Comment by twitchax** [comment]
Ok: done.  Will release soon-ish. :)
