### ISSUE TITLE
When using UseHttp, a trailing slash at the end of the URL will result in double slashes in the final URL, causing errors

### ISSUE THREAD

**Issue by Nysosis** [twitchax/AspNetCore.Proxy#48]
If I make a call to my app, with the URL '/the-proxied-url', and using the following configuration,

```csharp
	app.RunProxy((proxy) => proxy.UseHttp("https://myproxiedurl/"));
```

The actual URL generated to proxy to is: `https://myproxiedurl//the-proxied-url`, note the double slash, this could cause errors if the proxied server doesn't collapse them down.

**Comment by twitchax** [comment]
Thanks: I will fix soon™.

**Comment by twitchax** [comment]
Thinking through this, I may actually just make a note in the README.  Having the double slash is _technically_ still a valid URI.  I don't want to search the computed URIs for extra slashes, etc., especially when a user can make that decision in other parts of the string/path, and it is still valid.

**Comment by twitchax** [comment]
Nevermind, I decided to just trim it.
