### ISSUE TITLE
Is there a cleaner way to fallback to initial Host?

### ISSUE THREAD

**Issue by bnssoftware** [twitchax/AspNetCore.Proxy#49]
If a host falls through and doesn't need to be proxied based on set rules, rather than having to do this:

return "https://" + context.Request.Host.Value;

Can there be a cleaner way to just fallback to the initial request host?

**Comment by twitchax** [comment]
This library is just a [middlware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1), and you can place other routes in the middleware chain before this middleware.

You should add whatever routes/rules that you want the host to handle as `Use` middleware before the `UseProxy` or `RunProxy` middleware.
