### ISSUE TITLE
GET requests don't forward properly 

### ISSUE THREAD

**Issue by mvarga6** [twitchax/AspNetCore.Proxy#5]
I'm forwarding requests from a Gateway API to a microservice API that implements standard REST routes using proper verbage.  This seems to work fine for POST, PUT, PATCH requests but not for GET and DELETE.  I viewed the source and noticed the request body is copied into route params for these verbs. 

The simplest work-around I found was to send the exact request as POST and enable POST verb on the target routes.  

This seems like something that _should_ work without this work-around and might not be extraneous to enable. Does this seem like something easily fixable?

**Comment by twitchax** [comment]
@mvarga6, which line are you looking at that does a copy?

Are you passing a body in the `GET` that is not being forwarded?  If so, that is is not valid behavior, typically (see: https://stackoverflow.com/questions/978061/http-get-with-request-body).

If I am not understanding any of this correctly, then the best solution might be to look at the tests and give me an example test case that would fail based on this issue.

**Comment by twitchax** [comment]
@mvarga6, ping? :)

**Comment by mvarga6** [comment]
@twitchax Sorry for the delay.  No, I was not forwarding a body with the `GET`.  We've since change the design to not require this proxy but I will still try to provide the minimal code to reproduce.  I'll follow up with that a little later.

**Comment by twitchax** [comment]
Closing until there is a repro. :)

**Comment by drewdelano** [comment]
@twitchax I'm seeing a repro for DELETE, as @mvarga6 mentioned.

According to the MDN documentation it's allowed to have a body:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

I think I'm on the latest, but I'm not 100% sure.  I'll check in a moment.

**Comment by drewdelano** [comment]
Nevermind.  Turns out our use case is specifically undefined and should be avoided:
https://stackoverflow.com/a/60357432/1007701
