### ISSUE TITLE
Can I [Authorize] on Mapped proxy routes?

### ISSUE THREAD

**Issue by szalapski** [twitchax/AspNetCore.Proxy#53]
Is there any way to add an AuthorizeAttribute on `Map`ped proxy routes without creating a controller for them?

**Comment by twitchax** [comment]
@szalapski,interesting question.  Do you have a link or an example for this pattern in "vanilla" ASP.NET Core route mapping?

**Comment by szalapski** [comment]
Yes, here it is
<https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-3.1>.
If I have controllers with [Authorize(...)] on them, I would like to
convert them to .Map so that I can eliminate the controllers, but still
have authorization on them.

**Comment by twitchax** [comment]
I don’t see the `.Map` example in your link.  I might be missing it?

**Comment by szalapski** [comment]
Let's take the first example.

`
[Authorize(Roles = "Administrator")]
public class AdministrationController : Controller
{
}
`

Suppose inside of that method was nothing but a call to `this.HttpProxyAsync($...);`.  Is there or could there be any way to convert this to .Map syntax while still retaining the [Authorize] attribute on that route?

**Comment by twitchax** [comment]
@szalapski, maybe something like this health checks example?

**Comment by twitchax** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1

**Comment by szalapski** [comment]
You mean via middleware?  Middleware `.UseAuthorization` is already in place, and it needs attributes on methods and/or classes to determine what routes to subject to middleware.  Not sure how I could do this with a route requested with `Map`.

**Comment by twitchax** [comment]
@szalapski, were you able to work around this?

**Comment by szalapski** [comment]
Only with explicit controllers.

**Comment by twitchax** [comment]
Have you tried using `WithIntercept`?

```csharp
app.UseProxies(proxies => {
    proxies.Map(proxy => proxy.UseHttp("http://google/com/", http => http.WithIntercept(async context => {
        if(!context.User.IsInRole("Admin") /* Or whatever else you need to check here. */)
        {
            context.Response.StatusCode = 401;
            await context.Response.WriteAsync("You need to be an admin!");
            return true;
        }

        return false;
    })));
});
```

**Comment by szalapski** [comment]
Cool...I think that should work.

**Comment by twitchax** [comment]
Yeah, I can see that as being a problem, for sure.  Any specific reason you are trying to stay away from controllers?
