### ISSUE TITLE
[Authorize] attribute is ignored by proxy route

### ISSUE THREAD

**Issue by ElVisPL** [twitchax/AspNetCore.Proxy#6]
Hey @twitchax 

Is it somehow possible to deny not authorized requests?

`[Authorize]` attribute seems to be ignored for proxy method

**Comment by twitchax** [comment]
Hi @ElVisPL,

At present, this would be a bit difficult.  The proxying nature of the attribute is designed to work "outside" of MVC.  The only way to get attribute to work would be to put the proxying methods in a `Controller`.  Unfortunately, that comes with some baggage that I have yet to investigate.

I recently updated the definition for `UseProxy` to allow you to inspect the `HttpContext`.  At present, that is your best bet: inspect the `HttpContext` when the proxy method is called and complete authorization inside the proxy method.

If you have some suggestions, though, I would be happy to explore them: I may have missed something in my investigation.

**Comment by twitchax** [comment]
@ElVisPL, well, I still liked your idea, so I decided to run with it.

I did not explicitly try `Authorize`, but I exposed the proxying functionality as an extension method on `Controller`, which should work just fine.  Please check out the new readme and let me know how it works.

The commit is [here](https://github.com/twitchax/AspNetCore.Proxy/commit/f1f5eb823661a5433f84955f5c0af3d75e288e8d).

**Comment by ElVisPL** [comment]
@twitchax It works perfectly and brings whole new possibilities!

Do you plan to update nuget version in the near future?

**Comment by twitchax** [comment]
Yep: will do!

**Comment by twitchax** [comment]
@ElVisPL, just added a GitHub Action for releases and pushed to NuGet. :)

Thanks for the suggestion.
