### ISSUE TITLE
Unable to read data from the transport connection with form-data in body content

### ISSUE THREAD

**Issue by using-system** [twitchax/AspNetCore.Proxy#62]
Hello,

The library generates the error below in the case of a form-data POST (to send a file) : 

+		InnerException	{"Unable to read data from the transport connection: L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application.."}	System.Exception {System.IO.IOException}
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnectionPool.<SendWithNtConnectionAuthAsync>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__71.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at AspNetCore.Proxy.HttpExtensions.<ExecuteHttpProxyOperationAsync>d__0.MoveNext() in D:\Repos\AspNetCore.Proxy\src\Core\Extensions\Http.cs:line 52
   
   Unable to read data from the transport connection: L’opération d’entrée/sortie a été abandonnée en raison de l’arrêt d’un thread ou à la demande d’une application..
      at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.<FillAsync>d__87.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Net.Http.HttpConnection.<ReadNextResponseHeaderLineAsync>d__84.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<SendAsyncCore>d__53.MoveNext()
   

The web request : 

-		request	{Microsoft.AspNetCore.Http.DefaultHttpRequest}	Microsoft.AspNetCore.Http.HttpRequest {Microsoft.AspNetCore.Http.DefaultHttpRequest}
+		Body	{Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream}	System.IO.Stream {Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream}
+		BodyReader	{Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader}	System.IO.Pipelines.PipeReader {Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader}
		ContentLength	160102	long?
		ContentType	"multipart/form-data; boundary=--------------------------563955002773771530027173"	string
+		Cookies	{Microsoft.AspNetCore.Http.RequestCookieCollection}	Microsoft.AspNetCore.Http.IRequestCookieCollection {Microsoft.AspNetCore.Http.RequestCookieCollection}
-		Form	{Microsoft.AspNetCore.Http.FormCollection}	Microsoft.AspNetCore.Http.IFormCollection {Microsoft.AspNetCore.Http.FormCollection}
		Count	0	int
-		Files	Count = 1	Microsoft.AspNetCore.Http.IFormFileCollection {Microsoft.AspNetCore.Http.FormFileCollection}
-		[0]	{Microsoft.AspNetCore.Http.FormFile}	Microsoft.AspNetCore.Http.IFormFile {Microsoft.AspNetCore.Http.FormFile}
		ContentDisposition	"form-data; name=\"file\"; filename=\"IDENTITY_VALID.jpg\""	string
		ContentType	"image/jpeg"	string
		FileName	"IDENTITY_VALID.jpg"	string
+		Headers	{Microsoft.AspNetCore.Http.HeaderDictionary}	Microsoft.AspNetCore.Http.IHeaderDictionary {Microsoft.AspNetCore.Http.HeaderDictionary}
		Length	159886	long
		Name	"file"	string
+		Static members		
+		Non-Public members		
+		Raw View		
		Keys	{string[0]}	System.Collections.Generic.ICollection<string> {string[]}
+		Static members		
+		Non-Public members		
+		Results View	Expanding the Results View will enumerate the IEnumerable	
		HasFormContentType	true	bool
-		Headers	{Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders}	Microsoft.AspNetCore.Http.IHeaderDictionary {Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders}
		ContentLength	160102	long?
		Count	11	int
		HasConnection	true	bool
		HasTransferEncoding	false	bool
+		HeaderAccept	{*/*}	Microsoft.Extensions.Primitives.StringValues
+		HeaderAcceptCharset	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderAcceptEncoding	{gzip, deflate, br}	Microsoft.Extensions.Primitives.StringValues
+		HeaderAcceptLanguage	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderAccessControlRequestHeaders	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderAccessControlRequestMethod	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderAllow	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderAuthorization	{Bearer MTU7Mjc7ZldkUndPelA5Rw==}	Microsoft.Extensions.Primitives.StringValues
+		HeaderCacheControl	{no-cache}	Microsoft.Extensions.Primitives.StringValues
+		HeaderConnection	{keep-alive}	Microsoft.Extensions.Primitives.StringValues
+		HeaderContentEncoding	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderContentLanguage	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderContentLength	{160102}	Microsoft.Extensions.Primitives.StringValues
+		HeaderContentLocation	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderContentMD5	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderContentRange	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderContentType	{multipart/form-data; boundary=--------------------------563955002773771530027173}	Microsoft.Extensions.Primitives.StringValues
+		HeaderCookie	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderCorrelationContext	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderDNT	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderDate	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderExpect	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderExpires	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderFrom	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderHost	{localhost:64083}	Microsoft.Extensions.Primitives.StringValues
+		HeaderIfMatch	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderIfModifiedSince	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderIfNoneMatch	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderIfRange	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderIfUnmodifiedSince	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderKeepAlive	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderLastModified	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderMaxForwards	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderOrigin	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderPragma	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderProxyAuthorization	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderRange	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderReferer	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderRequestId	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderTE	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderTraceParent	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderTraceState	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderTrailer	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderTransferEncoding	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderTranslate	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderUpgrade	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderUpgradeInsecureRequests	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderUserAgent	{PostmanRuntime/7.26.2}	Microsoft.Extensions.Primitives.StringValues
+		HeaderVia	{}	Microsoft.Extensions.Primitives.StringValues
+		HeaderWarning	{}	Microsoft.Extensions.Primitives.StringValues
		HostCount	1	int
+		MaybeUnknown	Count = 2	System.Collections.Generic.Dictionary<string, Microsoft.Extensions.Primitives.StringValues>
+		Unknown	Count = 2	System.Collections.Generic.Dictionary<string, Microsoft.Extensions.Primitives.StringValues>
		_bits	549901043715	long
		_contentLength	160102	long?
		_isReadOnly	false	bool
+		Non-Public members		
-		Results View	Expanding the Results View will enumerate the IEnumerable	
+		[0]	{[Cache-Control, {no-cache}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[1]	{[Connection, {keep-alive}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[2]	{[Content-Type, {multipart/form-data; boundary=--------------------------563955002773771530027173}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[3]	{[Accept, {*/*}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[4]	{[Accept-Encoding, {gzip, deflate, br}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[5]	{[Authorization, {Bearer ******}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[6]	{[Host, {localhost:64083}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[7]	{[User-Agent, {PostmanRuntime/7.26.2}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[8]	{[Content-Length, {160102}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[9]	{[CorrId, {test}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		[10]	{[Postman-Token, {50784bcb-db9a-481f-bbed-a907293735b6}]}	System.Collections.Generic.KeyValuePair<string, Microsoft.Extensions.Primitives.StringValues>
+		Host	{localhost:64083}	Microsoft.AspNetCore.Http.HostString
-		HttpContext	{Microsoft.AspNetCore.Http.DefaultHttpContext}	Microsoft.AspNetCore.Http.HttpContext {Microsoft.AspNetCore.Http.DefaultHttpContext}
+		Connection	{Microsoft.AspNetCore.Http.DefaultConnectionInfo}	Microsoft.AspNetCore.Http.ConnectionInfo {Microsoft.AspNetCore.Http.DefaultConnectionInfo}
+		Features	{Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection<Microsoft.AspNetCore.Hosting.HostingApplication.Context>}	Microsoft.AspNetCore.Http.Features.IFeatureCollection {Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection<Microsoft.AspNetCore.Hosting.HostingApplication.Context>}
+		FormOptions	{Microsoft.AspNetCore.Http.Features.FormOptions}	Microsoft.AspNetCore.Http.Features.FormOptions
+		HttpContext	{Microsoft.AspNetCore.Http.DefaultHttpContext}	Microsoft.AspNetCore.Http.HttpContext {Microsoft.AspNetCore.Http.DefaultHttpContext}
+		Items	{Microsoft.AspNetCore.Http.ItemsDictionary}	System.Collections.Generic.IDictionary<object, object> {Microsoft.AspNetCore.Http.ItemsDictionary}
+		Request	{Microsoft.AspNetCore.Http.DefaultHttpRequest}	Microsoft.AspNetCore.Http.HttpRequest {Microsoft.AspNetCore.Http.DefaultHttpRequest}
+		RequestAborted	IsCancellationRequested = false	System.Threading.CancellationToken
+		RequestServices	{Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope}	System.IServiceProvider {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope}
+		Response	{Microsoft.AspNetCore.Http.DefaultHttpResponse}	Microsoft.AspNetCore.Http.HttpResponse {Microsoft.AspNetCore.Http.DefaultHttpResponse}
+		ServiceScopeFactory	{Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine}	Microsoft.Extensions.DependencyInjection.IServiceScopeFactory {Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine}
+		Session	'((Microsoft.AspNetCore.Http.DefaultHttpContext)((Microsoft.AspNetCore.Http.DefaultHttpRequest)request).HttpContext).Session' threw an exception of type 'System.InvalidOperationException'	Microsoft.AspNetCore.Http.ISession {System.InvalidOperationException}
		TraceIdentifier	"0HM1P6G564UED:00000001"	string
+		User	{System.Security.Claims.ClaimsPrincipal}	System.Security.Claims.ClaimsPrincipal
+		WebSockets	{Microsoft.AspNetCore.Http.DefaultWebSocketManager}	Microsoft.AspNetCore.Http.WebSocketManager {Microsoft.AspNetCore.Http.DefaultWebSocketManager}
+		Static members		
+		Non-Public members		
		IsHttps	false	bool
		Method	"POST"	string
-		Path	{/api/v1.0/*****}	Microsoft.AspNetCore.Http.PathString
		HasValue	true	bool
		Value	"/api/v1.0/*****"	string
+		Static members		
+		Non-Public members		
-		PathBase	{}	Microsoft.AspNetCore.Http.PathString
		HasValue	false	bool
		Value	""	string
+		Static members		
+		Non-Public members		
		Protocol	"HTTP/1.1"	string
-		Query	{Microsoft.AspNetCore.Http.QueryCollection}	Microsoft.AspNetCore.Http.IQueryCollection {Microsoft.AspNetCore.Http.QueryCollection}
		Count	0	int
		Keys	{string[0]}	System.Collections.Generic.ICollection<string> {string[]}
+		Static members		
+		Non-Public members		
-		Results View	Expanding the Results View will enumerate the IEnumerable	
		Empty	"Enumeration yielded no results"	string
-		QueryString	{}	Microsoft.AspNetCore.Http.QueryString
		HasValue	false	bool
		Value	""	string
+		Static members		
+		Non-Public members		
+		RouteValues	{Microsoft.AspNetCore.Routing.RouteValueDictionary}	Microsoft.AspNetCore.Routing.RouteValueDictionary
		Scheme	"http"	string
+		Static members		
+		Non-Public members		
![webrequest](https://user-images.githubusercontent.com/12829212/89408831-53eaa280-d721-11ea-8cbb-0bd4384b76a9.png)

Regards,

Matthieu

**Comment by twitchax** [comment]
Hello!

This is likely a dupe of #57, which we have been working on.  We will release a fix soon, but you might want to try checking out master and see if your issue is fixed with it.

**Comment by using-system** [comment]
Hello,
I confirm that it works by getting the latest master sources.
Thank you !

For my project which uses AspNetCore.Proxy I prefer use the nuget. A publication is planned for soon?

Regards,

Matthieu

**Comment by twitchax** [comment]
Yep!  Planning on later today.

**Comment by using-system** [comment]
Great ! 

I close this issue

Many thanks.

Matthieu
