### ISSUE TITLE
check for token before proxying request

### ISSUE THREAD

**Issue by Steffen-MLR** [twitchax/AspNetCore.Proxy#65]
Hi,

I want to check a token before proxying a request. I have this:
```csharp
[Route("forwarded-server/api/{targetEndpoint}")]
public Task CheckTokenAndProxy(string targetEndpoint)
{
    if (Request.Headers.TryGetValue("token", out StringValues token))
    {
       if (Validate(token)) return this.HttpProxyAsync($"https://forwarded-server/api/{targetEndpoint}");
    }
    return ?;
}
```

As you can see the questionmark, i dont know how to solve this. I tried to do `this.HttpProxyAsync("https://myserver/forwarded-server/forbidden")` and implement another route `with an IActionResult and a Forbid(), but this gives an SSL Error (The Certificate is Self-signed).

Is there either a way to solve this like I did by disabling ssl check for the proxy target or am I doing this completey wrong?

**Comment by twitchax** [comment]
I would just do something like.

```csharp
this.Response.StatusCode = 403;
// Write to headers or body if you want here.
return Task.CompletedTask;
```

**Comment by Steffen-MLR** [comment]
That is exactly what I needed, thank you!
