### ISSUE TITLE
Is it possible to use typical dynamic route parameters for the proxy maps?

### ISSUE THREAD

**Issue by aderderian** [twitchax/AspNetCore.Proxy#74]
For example, proxies.Map("{clientid}/api/{endpoint}", proxy => proxy.UseHttp((context, args) => ........

Does it only resolve {endpoint} as a dynamic route element?

**Comment by twitchax** [comment]
What do you mean by "only...as a dynamic route element"?

**Comment by aderderian** [comment]
I meant {endpoint} was a reserved token and it only resolved that, or can it work with other placeholders like {xyz} and {xyz?}. In short, does it follow .net core endpoint routing standards?

**Comment by twitchax** [comment]
Ahhhh: good question!

Yes, it uses all of the same routing mechanics.  Actually, it just calls `MapMiddlewareRoute`, and passes the route into that. :)

See [here](https://github.com/twitchax/AspNetCore.Proxy/blob/master/src/Core/Extensions/Basic.cs#L63).
