### ISSUE TITLE
how to pass state , parameter in between methods ?

### ISSUE THREAD

**Issue by odin88** [twitchax/AspNetCore.Proxy#79]
I want to write a cache logic based on what I get in WithIntercept().
So how do share the variable, state to WithAfterReceive() ?

**Comment by twitchax** [comment]
Yeah, you can use [`HttpContext.Items`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-5.0#httpcontextitems).
