### ISSUE TITLE
Reuse connection issue with SSL

### ISSUE THREAD

**Issue by aik0n** [twitchax/AspNetCore.Proxy#91]
Hi, I have an odd problem. Described at 
[Reuse connection error](https://stackoverflow.com/questions/71304539/aspnetcore-proxy-reuse-connection-error-message)

After some resolving phase SSRS in this case was published with SSL and an error was changed.
A current one is:

```
Request could not be proxied.

The SSL connection could not be established, see inner exception.
```

So, how to resolve this?
How I can log inner exception in this case?
I mean release published application. Is AspNetCore.Proxy lib has any options to use logger?
Should I add custom middleware logger?

**Comment by aik0n** [comment]
Appliation http - SSRS http - works
Appliation https - SSRS http - reuse connection issue
Appliation https - SSRS https (IP address) - certificate issue
Appliation https - SSRS https (DNS name) - reuse connection issue
Appliation https - SSRS https (ignore SSL errors) - reuse connection issue

So, how to resolve "reuse connection issue"?

**Comment by twitchax** [comment]
Hello!

Sorry, I was away on vacation, and I jsut now saw this.

The connection reuse issue probably has to do with `Keep-Alive` headers.  Can you try editing your `HttpClient`?  Try adding...

```csharp
myHttpClient.DefaultRequestHeaders.ConnectionClose = false;
```

**Comment by aik0n** [comment]
Hello.
Thanks for help. I added recomended settings and this not resolve the problem.
Also, I added a test proxy map route and have no problem with it.
So, the problem not in proxy lib, maybe network specific thing.

PS I use iframe with post action to application API
This request will be proxied with the can't reuse connection error

PPS HTTP Client configuration:

![image](https://user-images.githubusercontent.com/39758281/156883663-8243923a-a99b-413b-9940-1c8825e6327d.png)

**Comment by twitchax** [comment]
Ok, that was worth a try.  Kind of difficult to serving without a repro on my end.  Do you have a similar minimal case that you can share, but using a public endpoint?

**Comment by aik0n** [comment]
It is difficult to coordinate with all interested parties.
Just for tests I added ".WithBeforeSend()" and keep-alive header in it.
It is not resolve the issue but error was changed.
Researching in progress...

![image](https://user-images.githubusercontent.com/39758281/157072137-8553e2ea-776b-432b-a979-ba73f07f3056.png)

**Comment by twitchax** [comment]
Interesting: maybe something to do with [this](https://support.microsoft.com/en-us/topic/a-kerberos-authentication-fails-together-with-the-error-code-0x80090302-or-0x8009030f-on-a-computer-that-is-running-windows-server-2008-or-windows-vista-when-the-aes-algorithm-is-used-7c626c9c-8b41-bb98-2945-03e9d3621482)?

**Comment by aik0n** [comment]
Okay, finally I have works solution.
No issues in proxy lib. Details matter.
Thank you for this support and advices and great proxy package.

In details:
In my case was helpful add .WithBeforeSend() Later I will provide full config.
The error message "The function requested is not supported" also happens with wrong credentials (or blocked user)
I didn't install any kerberos or NTLM fixes, service packs.
In my case SSRS execution user was blocked after deploy to test environment. Also test env has different domain name. Miscommunications with other team members and human aspect :)

How SSRS was integrated
1. Application (ASP.NET Core MVC) -> Request to build HTML form with report parameters to SSRS. Parameters depends on user input and selections.
2. Web URL access to SSRS with HTTP POST (SSRS feature). So SSRS build report by it own and return result with built in controls, etc.
3. Application has access from external network SSL, VPN. SSRS has access only from internal network
4. This project proxy lib used to catch special formed URL from HTML form and redirected to internal SSRS
5. Rendered report displayed in iframe
6. Config hell ...
7. Profit :)

HttpClient initialization:

![image](https://user-images.githubusercontent.com/39758281/157647548-8f6612ac-0750-4f1d-8445-158ccba11534.png)


Proxy map initialization:

![image](https://user-images.githubusercontent.com/39758281/157650363-4bbf2ebb-2c23-46ab-bc1c-70a8c9b7c44f.png)

**Comment by twitchax** [comment]
Interesting: glad you got it figured out!
