### ISSUE TITLE
Character encoding problem in Content-Disposition section in HTTP POST body (multipart/form-data requests)

### ISSUE THREAD

**Issue by saliksaly** [twitchax/AspNetCore.Proxy#95]
Hi,

I have encountered interesting problem with proxying http post requests - when uploading files.

Content-Type: multipart/form-data is used and form values are each in it's own Content-Disposition section (the format is described here: https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2).

In Content-Disposition header, **characters in the filename value are malformed - different than in the original request**.

Example from testing:

## from the original request:
```
Content-Disposition: form-data; name="files"; filename="Abby Wynne - Jak se mít dobře.pdf"
Content-Type: application/pdf
```

## from the proxied request:
```
Content-Disposition: form-data; name="files"; filename="Abby Wynne - Jak se m�t dobre.pdf"
Content-Type: application/pdf
```

There is problem when using non-ascii characters in file name. Something with character encoding...

Before, I used ProxyKit (https://github.com/proxykit/ProxyKit). It's similar library - there was not this problem. It is not supported so I switched to AspNetCore.Proxy. It works without problems in my project (all traffic from one "light" application goes to other one, instead of some local endpoints).

Could you please throw an eye on this issue? :)

Thanks

**Comment by saliksaly** [comment]
> Yeah, cool. This is likely an easy fix. Will be even easier if you could add a failing test, and I will debug it.

OK, I will add the test.

**Comment by saliksaly** [comment]
Here is pull request for the failing test: #96

**Comment by twitchax** [comment]
Thanks: I should have time to take a look this weekend!

**Comment by twitchax** [comment]
Thanks!

**Comment by twitchax** [comment]
Where are you capturing those files that you diffed?

**Comment by twitchax** [comment]
The reason I ask is because I cannot repro.  When I forward the request to a an endpoint running in the same process by starting a background kestral server, the file name is correct.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/549523/171484483-64f2850e-bc5f-4a96-a4fc-bf2fbb64035a.png">

**Comment by twitchax** [comment]
@saliksaly, thoughts?

**Comment by saliksaly** [comment]
> Where are you capturing those files that you diffed?

Hi,

For comparison of behaviour, in all three cases the requests are sent to https://postman-echo.com/post (defined in https://github.com/saliksaly/proxy_http_post_multipard_bad_encoding_test/blob/master/Constants.cs).

You cannot repro? Ty to upload the same file with unicode characters in name in all three forms and you will see the difference...

**Comment by twitchax** [comment]
I think the problem is with `postman`, as a I said before.  Have you tried this with something other than postman?

**Comment by saliksaly** [comment]
No no, it is not the postman's problem.
Try again the test app: https://github.com/saliksaly/proxy_http_post_multipard_bad_encoding_test.
It now sends http posts to local application: https://github.com/saliksaly/proxy_http_post_multipard_bad_encoding_test (http://localhost:5141/file).

Here are the differences:

- Post file - direct - **file name ok**
![image](https://user-images.githubusercontent.com/16895897/172127576-967da030-446b-4591-8264-3b500706a4a9.png)
![image](https://user-images.githubusercontent.com/16895897/172127634-51a95499-5d6d-4e4e-98a0-a6b8bde8af46.png)
- Post file - through ProxyKit - **file name ok**
![image](https://user-images.githubusercontent.com/16895897/172127733-e25f377b-c20e-4352-934e-052a7ab5dcdd.png)
![image](https://user-images.githubusercontent.com/16895897/172127814-63a2e4ea-bbfb-46fd-ae4c-7dfaea634bf4.png)
- Post file - through AspNetCore.Proxy - **file name BAD**
![image](https://user-images.githubusercontent.com/16895897/172127925-d34c3b53-6932-4ad0-9d2c-47c25138dc80.png)
![image](https://user-images.githubusercontent.com/16895897/172127960-71edfa92-cfc9-4ace-96b5-f38128416dc3.png)


Could you try it on your own, please, to see the difference?

**Comment by twitchax** [comment]
That's the confusing part: I did try it on my own, and the `IFormFile` has the correct file name.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/549523/172233127-df123a25-1a47-45b3-a2e2-2a91c44360d7.png">

**Comment by twitchax** [comment]
Finally figured it out.  `HttpClient` uses an old school RFC for `Content-Disposition`, so I forced the header.

**Comment by twitchax** [comment]
New release is [here](https://github.com/twitchax/AspNetCore.Proxy/releases/tag/v4.4.0).

**Comment by saliksaly** [comment]
It already works! :-) 
Thank you, very much :)
